//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public string Subject { get; set; }
        public byte[] StartTime { get; set; }
        public System.DateTime ExamDate { get; set; }
        public int Duration { get; set; }
        public string ClassRoom { get; set; }
        public string Faculty { get; set; }
        public string Status { get; set; }
    }
}
